/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui90476;
import Controller90476.AllObjectController90476;
import Gui90476.*;
import Model90476.AllObjectModel90476;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author GENESIS
 */
public class SepatuGui90476 extends javax.swing.JFrame {
        
    /**
     * Creates new form JFrame1
     */
    public SepatuGui90476() {
        initComponents();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        LblJudul = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tabelDataSepatu = new javax.swing.JTable();
        LblMerk = new javax.swing.JLabel();
        LblUkuran = new javax.swing.JLabel();
        LblStok = new javax.swing.JLabel();
        TxtMerk = new javax.swing.JTextField();
        TxtUkuran = new javax.swing.JTextField();
        TxtStok = new javax.swing.JTextField();
        BtnTambah = new javax.swing.JButton();
        BtnUbah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        LblId = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        LblJudul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblJudul.setText("Sistim Informasi Gudang Sepatu");
        LblJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabelDataSepatu.setModel(viewSepatu());
        tabelDataSepatu.getTableHeader().setReorderingAllowed(false);
        tabelDataSepatu.setVerifyInputWhenFocusTarget(false);
        tabelDataSepatu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataSepatuMouseClicked(evt);
            }
        });
        scroll.setViewportView(tabelDataSepatu);

        LblMerk.setText("MERK");

        LblUkuran.setText("UKURAN");

        LblStok.setText("STOK");

        BtnTambah.setText("Tambah");
        BtnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnTambahMouseEntered(evt);
            }
        });
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnUbah.setText("Ubah");
        BtnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnUbahMouseEntered(evt);
            }
        });
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnBatal.setText("Batal");
        BtnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBatalMouseClicked(evt);
            }
        });
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        LblId.setText("ID");

        TxtId.setEnabled(false);

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(LblJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63))
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BtnTambah)
                        .addGap(29, 29, 29)
                        .addComponent(BtnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnHapus))
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblMerk)
                            .addComponent(LblUkuran)
                            .addComponent(LblStok)
                            .addComponent(LblId))
                        .addGap(26, 26, 26)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtMerk)
                            .addComponent(TxtUkuran)
                            .addComponent(TxtStok)
                            .addComponent(TxtId))))
                .addGap(22, 22, 22))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LblJudul)
                .addGap(18, 18, 18)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblId)
                            .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblMerk)
                            .addComponent(TxtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblUkuran)
                            .addComponent(TxtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblStok)
                            .addComponent(TxtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnTambah)
                            .addComponent(BtnUbah)
                            .addComponent(BtnHapus)
                            .addComponent(BtnBatal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelDataSepatuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataSepatuMouseClicked
        int i = tabelDataSepatu.getSelectedRow();
        String id = tabelDataSepatu.getModel().getValueAt(i,0).toString();
        TxtId.setText(id);
        String merk = tabelDataSepatu.getModel().getValueAt(i,1).toString();
        TxtMerk.setText(merk);
        String ukuran = tabelDataSepatu.getModel().getValueAt(i,2).toString();
        TxtUkuran.setText(ukuran);
        String stok = tabelDataSepatu.getModel().getValueAt(i,3).toString();
        TxtStok.setText(stok);
        
        BtnTambah.setVisible(false);
        BtnBatal.setVisible(true);
        BtnUbah.setVisible(true);
        BtnHapus.setVisible(true);
    }//GEN-LAST:event_tabelDataSepatuMouseClicked

    private void BtnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBatalMouseClicked
        
    }//GEN-LAST:event_BtnBatalMouseClicked

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
       
       kosong();
       tabelDataSepatu.setModel(viewSepatu());
       BtnTambah.setVisible(true);
       BtnUbah.setVisible(false);
       BtnHapus.setVisible(false);
       BtnBatal.setVisible(false);
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        if("".equals(TxtMerk.getText()) && "".equals(TxtUkuran.getText()) && "".equals(TxtStok.getText())){
             JOptionPane.showMessageDialog(null, "Inputan masih ada yang kosong", "information", JOptionPane.INFORMATION_MESSAGE);
        }else{
           try{
                    int id = 0;
                    String merk = TxtMerk.getText();
                    String ukuran = TxtUkuran.getText();
                    String stok = TxtStok.getText();
                    AllObjectController90476.sepatu.insertSepatu90476(id, merk, ukuran, stok);
                    tabelDataSepatu.setModel(viewSepatu());
                     kosong();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Format ada yang salah", "information", JOptionPane.INFORMATION_MESSAGE);
                     kosong();
                }
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        if("".equals(TxtMerk.getText()) && "".equals(TxtUkuran.getText()) && "".equals(TxtStok.getText())){
           JOptionPane.showMessageDialog(null, "Inputan masih ada yang kosong", "information", JOptionPane.INFORMATION_MESSAGE);
        }else{
             try{
                    int id = Integer.parseInt(TxtId.getText());
                    String merk = TxtMerk.getText();
                    String ukuran = TxtUkuran.getText();
                    String stok = TxtStok.getText();
                    AllObjectController90476.sepatu.updateSepatu90476(id, merk, ukuran, stok);
                    tabelDataSepatu.setModel(viewSepatu());
                     kosong();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Format ada yang salah", "information", JOptionPane.INFORMATION_MESSAGE);
                     kosong();
                }
            
        }
    }//GEN-LAST:event_BtnUbahActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if("".equals(TxtId.getText())){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus", "information", JOptionPane.INFORMATION_MESSAGE);
        } else{
        int i = Integer.parseInt(TxtId.getText());
                    int result = JOptionPane.showConfirmDialog(null, "Yakin Id "+i+" Akan Hapus ?", null, JOptionPane.YES_NO_OPTION);
                    if(result == JOptionPane.YES_OPTION){
                        AllObjectController90476.sepatu.deleteSepatu90476(i);
                        tabelDataSepatu.setModel(viewSepatu());
                        kosong();
                    }else{
                        kosong();                       
                    }
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTambahMouseEntered
        if("".equals(TxtMerk.getText())){
            BtnTambah.setBackground(Color.red);
        }else{
            BtnTambah.setBackground(Color.green);
        }
    }//GEN-LAST:event_BtnTambahMouseEntered

    private void BtnUbahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUbahMouseEntered
       if("".equals(TxtMerk.getText())){
            BtnUbah.setBackground(Color.red);
        }else{
            BtnUbah.setBackground(Color.green);
        }
    }//GEN-LAST:event_BtnUbahMouseEntered

    
    public DefaultTableModel viewSepatu(){
        DefaultTableModel dataSepatu = new DefaultTableModel();
        Object[] kolom = {"ID","Merk", "Ukuran", "Stok"};
        dataSepatu.setColumnIdentifiers(kolom);
        int panjang = AllObjectModel90476.sepatuModel.getSepatuEntity90476().size();
        for(int i=0;i<panjang;i++){
            Object[] sepatu = new Object[4];
            sepatu[0] = AllObjectModel90476.sepatuModel.getSepatuEntity90476().get(i).getId90476();
            sepatu[1] = AllObjectModel90476.sepatuModel.getSepatuEntity90476().get(i).getMerk90476();
            sepatu[2] = AllObjectModel90476.sepatuModel.getSepatuEntity90476().get(i).getUkuran90476();
            sepatu[3] = AllObjectModel90476.sepatuModel.getSepatuEntity90476().get(i).getStok90476();
            dataSepatu.addRow(sepatu);
        }
        return dataSepatu;
    }
    
    public void kosong(){
        TxtId.setText(null);
        TxtMerk.setText(null);
        TxtUkuran.setText(null);
        TxtStok.setText(null);
        BtnBatal.setVisible(false);
        BtnUbah.setVisible(false);
        BtnHapus.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JLabel LblId;
    private javax.swing.JLabel LblJudul;
    private javax.swing.JLabel LblMerk;
    private javax.swing.JLabel LblStok;
    private javax.swing.JLabel LblUkuran;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtMerk;
    private javax.swing.JTextField TxtStok;
    private javax.swing.JTextField TxtUkuran;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabelDataSepatu;
    // End of variables declaration//GEN-END:variables
}
